### ISSUE TITLE
test_tpm2_unseal.sh ContextLoad Error. TPM Error:0x902

### ISSUE THREAD

**Issue by rrottmann** [PaulKissinger/LetsTrust#10]
After cloning the latest code and executing `Scripts/tpm2_install.sh`I execute the following test code from the repo and receive a `ContextLoad Error`:

```bash
root@raspberrypi:/home/pi/git/LetsTrust/Scripts/tpm2-tools/test/system# cat /etc/debian_version
10.3
root@raspberrypi:/home/pi/git/LetsTrust/Scripts/tpm2-tools/test/system# uname -a
Linux raspberrypi 4.14.98+ #1200 Tue Feb 12 20:11:02 GMT 2019 armv6l GNU/Linux
root@raspberrypi:/home/pi/git/LetsTrust/Scripts/tpm2-tools/test/system#./test.sh test_tpm2_unseal.sh
-ERROR: ContextLoad Error. TPM Error:0x902
ERROR: Unable to run tpm2_unseal
tpm2_unseal -Q -c $file_unseal_key_ctx -o $file_unseal_output_data on line 79 failed: 1
test_tpm2_unseal.sh ... FAILED
Tests passed: 0
Tests Failed: 1
Fail summary:

test_tpm2_unseal.sh
```
My goal is to create command snippets for basic operations like sign/verify or seal/unseal.

I follow the basic guidelines of how to work with a TPM but it seems that `tpm2-tools` changes parameters quite often and I cannot follow the examples from the man page or code snippets I find online without modification. So I thought that maybe the test suite contains a source of truth that I can use for troubleshooting.

The module works so far as I could create a seal object manually by executing:

```bash
mkdir -p /tmp/tpm && cd /tmp/tpm
# clear tpm and take ownership
tpm2_takeownership -c
# create a primary object (rsa key)
tpm2_createprimary --hierarchy=o --halg=sha256 --kalg=rsa --context=prim.ctx
# store rsa key in persistent tpm region
tpm2_evictcontrol --auth=o --context=prim.ctx --persistent 0x81010001
# seal secret key in tpm - step 1 create seal object of random secret
head -c 32 /dev/urandom | base64 | tpm2_create --halg sha256 --kalg keyedhash --pubfile seal.pub --privfile seal.priv --in-file - --context-parent prim.ctx
# ...
# profit
```
Is there currently a bug or is there some error in my approach? Would it be possible to document some basic examples of how to work with the LetsTrust module?

**Comment by PaulKissinger** [comment]
Hi @rrottmann, 

i compleatly overssen this issue,


regards the command tpm2_takeownership is deprecated, i'll close the issue.

the 0x902 is an  Warning (2.0): TPM_RC_OBJECT_MEMORY, maybe you restart your script a little bit to often an the momery on the TPM was running out.


To you question, here is a good guide for the initial usage of an SLB9670 or SLB9762.

https://www.infineon.com/cms/en/product/gated-document/optiga-tpm-rpi-quickstarter-user-guide-8ac78c8c8e7ead30018ee5a4d85b04bd/


Best Regards,


Paul
