### ISSUE TITLE
purpose of IRQ pin?

### ISSUE THREAD

**Issue by gluonplasma** [PaulKissinger/LetsTrust#12]
I'm working on an update to a custom board with the Pi Compute Module to add TPM.  What is the purpose of the IRQ pin?  Our board already has that pin (GPIO 25 on the hat) used for something else. From my understanding the TPM module shouldn't interrupt any processes and only responds when asked for data.  The datasheet for the Infineon SLB9670 isn't clear why it's needed, and looking through the overlay, there isn't a GPIO pin specified for the IRQ, which makes me think it's not used.  Any input would be appreciated.

**Comment by PaulKissinger** [comment]
Hi, @gluonplasma, the IRQ pin of the SLB9670 could used to check is an operation ready. For TPM 1.2 it was usefully, but for 2.0 you can manage these behavior over the software stack. 
So for your Project: Pullup this pin with 10k and ignore it :) 

Bye for now
