### ISSUE TITLE
Summarizing TPM tools with brief comparison 

### ISSUE THREAD

**Issue by tomoveu** [PaulKissinger/LetsTrust#6]
Hello Paul,

I am one of the creators of TPM Developer Community with the goal to make Developer-friendly Trusted Computing. We are summarizing the TPM tools with brief comparison and our newest member actually reference your blog page :-) 

Would it be okay to summarize the information from your blog on the Community website?

Would be great to join us and participate - https://developers.tpm.dev The website is in early stage, but I am committed to adding all proposal for TPM tools on www.tpm.dev in an easy to compare, so people could find the best tool for their TPM challenge.

ps: This is an issue of type "question", but Github does not allow me to qualify it myself ;-)

Thanks,
Dimi

**Comment by PaulKissinger** [comment]
Solved on 4 Dec 2019
