### ISSUE TITLE
Upload LetsTrust-TPM to easyeda.com

### ISSUE THREAD

**Issue by rgl** [PaulKissinger/LetsTrust#9]
Just found out about your [LetsTrust-TPM](https://letstrust.de/archives/29-New-fun-fact!.html) board/project, pretty interesting. I'm ordering one of those boards to try it out.

To make the design more easily incorporated in other boards, what do you think about uploading the schematics/pcb into https://easyeda.com/?

**Comment by PaulKissinger** [comment]
Hi rgl,

the schematics you will find on www.LetsTrust.de

Direct links you will find here: 
https://letstrust.de/uploads/letstrust-v2.2.placement.cs1.pdf
https://letstrust.de/uploads/letstrust-v2.2.schematic.pdf
